### PR TITLE
fixes for some hosting service

### PR DESCRIPTION
**Pull request by WesleyVanNeck**
fix some sertend hosts were not able to run it

### CODE REVIEW

**Comment by lukeeey** [comment]
Then the server hosts are shit. Leave it as config

**Comment by RednedEpic** [comment]
I’m interested to know which host causes issues with this.

**Comment by WesleyVanNeck** [comment]
@RednedEpic  zap hosting
 at least my host doesnt allow the config toi be craeted as config.yml but it doesnt support geyser originaly so i use bungee slot

**Comment by WesleyVanNeck** [comment]
https://zap-hosting.com/

**Comment by RednedEpic** [comment]
> @RednedEpic zap hosting
> at least my host doesnt allow the config toi be craeted as config.yml but it doesnt support geyser originaly so i use bungee slot

I think you’d be better off opening a ticket on their end.

**Comment by WesleyVanNeck** [comment]
> > @RednedEpic zap hosting
> > at least my host doesnt allow the config toi be craeted as config.yml but it doesnt support geyser originaly so i use bungee slot
> 
> I think you’d be better off opening a ticket on their end.

i dont really that thats a good idea i will fork and keep that fork uptodate like pspe then

**Comment by RednedEpic** [comment]
If your host is deleting your configuration files, this sounds like a major issue on their end. I’d open a ticket if I were you.

**Comment by WesleyVanNeck** [comment]
@RednedEpic  no it add somting to config that geyser dont like
so ass the query

**Comment by WesleyVanNeck** [comment]
that make so the config crashes and config cant be made

**Comment by WesleyVanNeck** [comment]
it adds this query_port: 25566

**Comment by lukeeey** [comment]
Set FAIL_ON_UNKNOWN_PROPERTIES to false

**Pull request closed without merging**
