### PR TITLE
Update bungeecord-api to 1.16-R0.4-SNAPSHOT

### PR DESCRIPTION
**Pull request by EddieDiamondFire**
No one seems to update so I'm doing it here.

### CODE REVIEW

**Comment by YHDiamond** [comment]
I think there is a reason why they aren't updating it yet.

**Comment by Camotoy** [comment]
No, there isn't expressly a reason not to update since BungeeCord has to be on latest to accept the latest.

**Comment by YHDiamond** [comment]
Ok then, so are we updating?

**Comment by Camotoy** [comment]
I'd need to look if there are any adverse side effects, or if anyone else on the team is more knowledgeable with BungeeCord they're free to handle it.

**Review by lukeeey — APPROVED** [review]
It compiles so it should be fine. Had a quick look and the API doesn't seem to have changed much, mostly RGB color support (but the enum methods like `ordinal()` were replicated)

**Comment by Camotoy** [comment]
Sounds good, thanks for the second review. Realistically, we don't use much of the API anyway. If BungeeCord people start to complain, we know where to look.

Also, the API did get bumped to R0.5 but since R0.4 is still compatible, this is the best way to go.

**Comment by Camotoy** [comment]
Thanks!

**Comment by EddieDiamondFire** [comment]
Just to be safe I tested it on Bungeecord and Waterfall to see if there's any issues. So far there's none

**Pull request merged**
