### PR TITLE
Send your ip as plugin message

### PR DESCRIPTION
**Pull request by JH3Y50N**
i don't know if this work, my eclipse don't load the maven project i only code finding by class and method name but i want ips of users

### CODE REVIEW

**Comment by DoctorMacc** [comment]
Is Floodgate not an option for you?

**Comment by JH3Y50N** [comment]
> Is Floodgate not an option for you?

no

**Comment by D3ATHBRINGER13** [comment]
This may lead to a lot of spam but turning on debug mode shows the IPs of connecting players

**Comment by DoctorMacc** [comment]
Unfortunately, as this does not compile and Floodgate achieves this already, I'm going to close it. If you want this to be implemented, I would recommend:

- Submitting a working PR
- Making a feature request.

**Pull request closed without merging**
