### PR TITLE
Update IDs

### PR DESCRIPTION
**Pull request by D3ATHBRINGER13**
There were a few MCEE block/item IDs missing

### CODE REVIEW

**Comment by DoctorMacc** [comment]
I'm going to close this because this is a PR for the Mappings repository. We likely don't need these items since Geyser does not deal with MCEE in its current state.

**Comment by D3ATHBRINGER13** [comment]
Should I add this as a PR for the mappings module as, as far as I can tell going to support MCEE at some point, or not?
Or you could do it I guess

**Comment by DoctorMacc** [comment]
We are, but I don't think mappings are an issue. Tagging @bundabrg since he is the one leading that charge.

**Comment by bundabrg** [comment]
Would you mind PR'ing to my mappings repo @D3ATHBRINGER13. https://github.com/bundabrg/mappings-education

**Comment by D3ATHBRINGER13** [comment]
yeah sure, just gimme a sec

**Comment by bundabrg** [comment]
I should add its unlikely those entities will ever be seen even on an MCEE as we still attach to a java server which is never going to send or receive them however its probably good to be complete.

**Comment by D3ATHBRINGER13** [comment]
yeah, sorry i'll have to do that tomorrow, as it is 3:01 am here

**Pull request closed without merging**
