### PR TITLE
Block states and fix waterlogged blocks

### PR DESCRIPTION
**Pull request by AJ-Ferguson**

### CODE REVIEW

**Comment by RednedEpic** [comment]
From my testing, everything appears to work fine (new 1.15 blocks included and waterlogged blocks), except the bubbles that come off of soul sand/magma blocks don't appear to be waterlogged. bubbles

**Comment by EOT3000** [comment]
bubbles are also reversed. Magma bubbles push you up, while soul sand push you down. On java its reverse.

**Comment by RednedEpic** [comment]
> bubbles are also reversed. Magma bubbles push you up, while soul sand push you down. On java its reverse.

In the screenshot I sent, there was magma. The bubbles pushed me up there, so I believe that's fine.

**Comment by EOT3000** [comment]
hm, when I tested It it was wrong. Oh well

**Comment by RednedEpic** [comment]
Did some more testing and it appears the bugs I mentioned above are resolved.

**Pull request merged**
