### PR TITLE
Fix Merchant Inventory Transaction

### PR DESCRIPTION
**Pull request by bundabrg**
Add fix for Villager Trading

### CODE REVIEW

**Comment by DoctorMacc** [comment]
!start-test-server

**Comment by Heath123** [comment]
This works for me

**Comment by DoctorMacc** [comment]
Works fine on the test server; I could not take emeralds out of the slot though (did not test with a villager with two slots)

**Comment by bundabrg** [comment]
Good to know. I'll look at that tomorrow.

**Comment by bundabrg** [comment]
Ok, so far #763 works perfectly. This one has an issue on a tablet where when trading the source item is left in the cursor (or more likely it thinks its in the cursor). I suspect its related to a refresh after the click or perhaps Geyser thinks the cursor has something in it when java does not.

**Comment by DoctorMacc** [comment]
!start-test-server

**Comment by DoctorMacc** [comment]
!stop-test-server

**Comment by DoctorMacc** [comment]
!start-test-server

**Comment by DoctorMacc** [comment]
Works fine for me on desktop.

**Comment by DoctorMacc** [comment]
As villager trading is hotly requested for a fix, I'll be merging this until the inventory rewrite is finished. Thanks for looking into this!

**Pull request merged**
