### PR TITLE
Fix new minecart with block breaking furnace minecart display

### PR DESCRIPTION
**Pull request by rtm516**
This moves the DISPLAY_ITEM part of the minecart entity to a separate class and not the base entity to prevent issues with things such as furnace minecarts not displaying properly after #713 was merged.

### CODE REVIEW

**Comment by rtm516** [comment]
But we shouldn't set the display for the other minecart types only the normal hence the sperate class for it

**Comment by rtm516** [comment]
@SinanGentoo what is that showing? Not sure if this is proof of it fixing the issue or another bug.

**Comment by DoctorMacc** [comment]
https://wiki.vg/Entity_metadata#MinecartFurnace all minecarts inherit from the base minecart class - unless setting the display block messes with the other entities (which, of course, would be the minecart furnace) I think it would be cleanest to not require a separate class.

**Comment by rtm516** [comment]
Done

**Comment by DoctorMacc** [comment]
I'll test this shortly and then merge it.

**Pull request merged**
