### PR TITLE
Improve Quality of Logo

### PR DESCRIPTION
**Pull request by Legit4K**
I've removed the gap on the left & improved the quality

### CODE REVIEW

**Comment by baxandrei** [comment]
I don't know if I'm allowed to give my opinion, but to be honest, I like the old one more ... In my opinion you can not call it quality improvement since it is identical to the old and larger resolution scale. And the left side looks very ugly.

**Comment by Legit4K** [comment]
Really? :thinking: for me, my updated version seems sharper

**Comment by JustTalDevelops** [comment]
Yeah, it looks awful on my setup. I'd stick to the current.
image

**Comment by Legit4K** [comment]
Alright

**Pull request closed without merging**
