### PR TITLE
Disable namespaced commands

### PR DESCRIPTION
**Pull request by rtm516**
This might fix the freezing issue as pointed out by @LegacyGamerHD

### CODE REVIEW

**Comment by DoctorMacc** [comment]
I still got a little freeze while using this PR. If you can test this using a device that can crash when opening commands, please do.

**Comment by SinanGentoo** [comment]
Is it possible to control the display of commands brought by the plugin in config.yml?

**Comment by DoctorMacc** [comment]
@SinanGentoo this is a viable option.

**Comment by rtm516** [comment]
Superseded by https://github.com/GeyserMC/Geyser/pull/598

**Pull request closed without merging**
