### PR TITLE
Sending player ip with a plugin message

### PR DESCRIPTION
**Pull request by JH3Y50N**
Send user ip as plugin message, this maybe work

### CODE REVIEW

**Comment by Tim203** [comment]
No, this will break stuff.
Plus minecraft:brand is meant to identify a specific client, so it shouldn't contain things that can change, such as an IP-address.

**Comment by JH3Y50N** [comment]
> No, this will break stuff.
> Plus minecraft:brand is meant to identify a specific client, so it shouldn't contain things that can change, such as an IP-address.

i can't use floodgate on my Waterfall..

`[07:09:29 INFO]: [/127.0.0.1:63187] <-> InitialHandler has connected
[07:09:29 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@7a56812e, id=8, owner=org.geysermc.floodgate.BungeePlugin@1059754c, task=org.geysermc.floodgate.BungeePlugin$$Lambda$291/1063784648@7f80557c, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException: null
        at org.geysermc.floodgate.util.ReflectionUtil.makeAccessible(ReflectionUtil.java:160) ~[?:?]
        at org.geysermc.floodgate.util.ReflectionUtil.getValue(ReflectionUtil.java:54) ~[?:?]
        at org.geysermc.floodgate.util.ReflectionUtil.getValue(ReflectionUtil.java:64) ~[?:?]
        at org.geysermc.floodgate.BungeePlugin.lambda$onPreLogin$0(BungeePlugin.java:115) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_202]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]`

**Comment by rtm516** [comment]
> I can't use floodgate on my Waterfall.

That error will be caused by changes to the waterfall source so unless they changed something recently you're using a custom fork and that is likely the issue.
We rely on `ch` existing inside the connection, please see the below line for how that's done:
https://github.com/GeyserMC/Floodgate/blob/development/bungee/src/main/java/org/geysermc/floodgate/BungeePlugin.java#L115

**Comment by zimzaza4** [comment]
> Send user ip as plugin message, this maybe work
Maybe Geyser-Spigot can

**Pull request closed without merging**
