### PR TITLE
Armor stand fixes

### PR DESCRIPTION
**Pull request by Camotoy**
- Armor stands now show armor if invisible. This allows both names and armor to show on an armor stand, and should allow for custom models that use armor stands to show, to an extent. I've been unable to find a custom model plugin at this time so verification on this would be great.
- Armor stand orientation when visible is now correct.

### CODE REVIEW

**Review by RednedEpic — APPROVED** [review]

**Comment by Technoguyfication** [comment]
I noticed armor stands with nametags work fine with Bedrock on PC and Mobile, but on Xbox (possibly PS4 and Switch too) they aren't visible. Will this fix those inconsistencies and allow armor stand names to show on Xbox?

**Comment by Camotoy** [comment]
Note: https://github.com/GeyserMC/Geyser/commit/047bf5f0f473c48d2b452fc4dfe1cdb11a0f9d7b may make something here irrelevant.

**Comment by Technoguyfication** [comment]
Is there anything blocking this PR from being merged?

**Comment by Camotoy** [comment]
I'm simple concerned about performance implications.

**Comment by bobhenl** [comment]
Hopefully will be merged soon...

**Pull request merged**
