### PR TITLE
Fix crash after first disconnect

### PR DESCRIPTION
**Pull request by AJ-Ferguson**

### CODE REVIEW

**Comment by RednedEpic** [comment]
Does this also allow the client to be reconnected and successfully be able to log in afterward?

**Comment by AJ-Ferguson** [comment]
Yes I tested it.

**Comment by RednedEpic** [comment]
This appears to have no effect on my testing. I don't crash (never did) when trying to rejoin, but I'm still unable to reconnect.

**Comment by AlissonLauffer** [comment]
> This appears to have no effect on my testing. I don't crash (never did) when trying to rejoin, but I'm still unable to reconnect.

Here I tested and successfully rejoined after disconnect

**Comment by RednedEpic** [comment]
Apologies, I tested with the wrong jar. Can confirm that this is fully working now.

**Comment by EOT3000** [comment]
That  must be so annoying

just add a .copy()

lol

**Pull request merged**
