### PR TITLE
Fix compiling hybrid

### PR DESCRIPTION
**Pull request by WesleyVanNeck**

### CODE REVIEW

**Comment by SupremeMortal** [comment]
The JRakNet dependency shouldn't be included anyway.

**Comment by lukeeey** [comment]
This is well funny

**Comment by WesleyVanNeck** [comment]
@SupremeMortal @lukeeey  idk I just fix a mestake

**Comment by lukeeey** [comment]
Sorry its not about your code its just funny how they need all this code for such a simple thing

**Comment by Tim203** [comment]
It is far from final, I said to Fly; post what you made, so we can help you

**Comment by EOT3000** [comment]
I need JRakNet. Supreme's raknet is too confusing for me lol. There's also the problem that the right udp packet isn't being sent

**Pull request closed without merging**
