### PR TITLE
Various entity fixes

### PR DESCRIPTION
**Pull request by rtm516**
Fixes a variety of entity related bugs:
- [x] Hitboxes (Fixes: https://github.com/GeyserMC/Geyser/issues/528)
- [x] Small and marker armour stands
- [x] Lingering potions
- [x] Invisible entity name tags still visible
- [x] Baby hitbox size 
- [x] Squid animation
- [x] Guardian beam target if its the local player
- [x] Wither boss head targets and shield (needs NukkitX/Protocol update)
- [x] Fishing line attach to entities

### CODE REVIEW

**Comment by TheMasterBlaster** [comment]
I have noticed that these changes seem to break custom nameplates (Atleast on the server I use for testing) when using as standalone.

image

The top name and the amount of health below it are what is meant to be seen but these changes seems to remove them and only shows the real Nameplate (which should not be visible)

**Comment by rtm516** [comment]
What plugin are you using for that?

**Comment by TheMasterBlaster** [comment]
The Plugin is called TAB v2.7.4

**Comment by rtm516** [comment]
> The Plugin is called TAB v2.7.4

Can't replicate this please message me on Discord, with configs and setup so I can replicate it

**Pull request merged**
