### PR TITLE
Use minecart chest and minecart hopper inventories (WIP, testing needed)

### LINKED ISSUE #696: Can't open GUI for moving players
**Describe the bug**

If a player is moving rapidly, the GUI which should open won't show up
**To Reproduce**

1. Use what ever menu plugin
2. move rapidly when trying to open a gui
3. see error

**Expected behavior**

GUI open as usual
**Screenshots / Videos**

None
**Server Version**

Paper version git-Paper-322

**Geyser Version**

Geyser pull request for inventory fix #602 
**Minecraft: Bedrock Edition Version**

1.14.6 all platform
**Additional Context**

### PR DESCRIPTION
**Pull request by Heath123**
Fixes #696
This means that for single chests, shulker boxes and hoppers a block doesn't need to be placed above the player's head. Todo:
- [ ] Merge changes from #517 
- [ ] Get people to test it

### CODE REVIEW

**Comment by AnonAlpha** [comment]
This will fix GUI issue, just tested ;-)

**Comment by Heath123** [comment]
Note: there are still issues if the player teleports a long way in one go

**Comment by Heath123** [comment]
I haven't tested the fixes for the merge conflicts

**Comment by Heath123** [comment]
Huh, it's a checksum validation error?

**Comment by AnonAlpha** [comment]
Not a code error I think, I build it successfully using GitPod

**Comment by ChiAkuma** [comment]
where can i test this?

**Comment by ExusiaiMoe** [comment]
> where can i test this?

Github Action build file

**Comment by Heath123** [comment]
> where can i test this?

This is really old, so that's probably not a great idea

**Comment by ExusiaiMoe** [comment]
> > where can i test this?
> 
> This is really old, so that's probably not a great idea

That's true

**Comment by RednedEpic** [comment]
Closing due to lack of activity + codebase is entirely different. Feel free to rebase & reopen if you still wish to implement this 🙂

**Pull request closed without merging**
