### PR TITLE
Fix renaming of colored items

### PR DESCRIPTION
**Pull request by ForceUpdate1**
Fixes issue with renaming of colored items

msQEDin

### CODE REVIEW

**Comment by rtm516** [comment]
Does this work with the new RGB colour codes? in Essentials you can use `&#FF0000` for red

**Comment by ForceUpdate1** [comment]
Essentails must also translate it into the json components. Minecraft has no legacy format for rgb colors

**Comment by DoctorMacc** [comment]
!start-test-server

**Comment by DoctorMacc** [comment]
Anvil is still bugged on the test server.

**Comment by ForceUpdate1** [comment]
!start-test-server

**Comment by ForceUpdate1** [comment]
!start-test-server

**Comment by EasyClifton** [comment]
Only Camotoy and rtm516 can do this, iirc.

**Comment by LegacyGamerHD** [comment]
!start-test-server

**Comment by Tim203** [comment]
@EasyClifton no, collaborators and higher

**Comment by EasyClifton** [comment]
Ok. I actuallt thought it was Developer and up.

**Comment by DoctorMacc** [comment]
!stop-test-server

**Comment by DoctorMacc** [comment]
!start-test-server

**Comment by ForceUpdate1** [comment]
!stop-test-server

**Comment by DoctorMacc** [comment]
!stop-test-server

**Comment by ForceUpdate1** [comment]
Thanks

**Comment by DoctorMacc** [comment]
!start-test-server if you need it.

**Comment by DoctorMacc** [comment]
!start-test-server

**Comment by ForceUpdate1** [comment]
it works tm now

**Comment by ForceUpdate1** [comment]
!stop-test-server

**Comment by DoctorMacc** [comment]
I'm going to merge this over Bund's fix as I believe properly serializing is a far cleaner option than a `try/catch`.

**Comment by DoctorMacc** [comment]
On second thought - the chat color changes will need another look through. I'll be pushing the NPE fix separately so we can get that out of the way.

**Comment by Camotoy** [comment]
It appears this will be obsolete with the inventory rewrite. Thank you for making a PR anyway!

**Pull request closed without merging**
