### PR TITLE
Fireball and ghast improvements

### PR DESCRIPTION
**Pull request by DoctorMacc**
- Ghasts now visually show if they're charging a fireball
- Fireballs are now vastly better and will update better

### CODE REVIEW

**Comment by zimzaza4** [comment]
Does this include dragon fireball?

**Comment by toinouH** [comment]
> Does this include dragon fireball? 

That's a good question.

**Comment by rtm516** [comment]
Just checked the code and yes it should include all 3 fireballs. Normal/Ghast, Dragon and small.

**Comment by vijaypondini** [comment]
I've tested ghast fireballs
So I've tested this on both java and bedrock. As usual java works like a beauty, knocking back fireballs as we please.
Bedrock faces a _bit of an _issue__ where the fireball does knock back, but it still ends up exploding?
I am unsure about what really happens on bedrock, it kinda glitches when im trying to punchback ( i was spam clicking ), and not very often does it actually move back and not explode

Here's a video on java - https://imgur.com/a/mNE4Exi ( it looks all cool, clean animations. )

On bedrock - https://imgur.com/a/5LI4ES1 ( the first fireball i was able to knock back by a LOT of spam clicking, the second one actually did get knocked back, but just exploded instead xD. And then after a while ghast moved far out that the game didn't render it, and well, invisible fireballs shot at me lol )

I will test ender dragon fireballs now :)

**Comment by vijaypondini** [comment]
Oh yeah, i am running latest paper software, and using geyser-spigot for this 

So i just tested dragon fireballs now, happy to say it worked well :)

Here it is on java - https://imgur.com/a/27C9hhq

and on bedrock, it's perfect. The effect when it lands on the ground is also very nice :) - https://imgur.com/a/IPD02hm ( another fireball was shot at me at the end of the recording too lol )

**Review by rtm516 — APPROVED** [review]

**Comment by vijaypondini** [comment]
Ready to merge? Note that I haven't tested it on consoles though. I can test on my xbox one but we better ask ps4 and switch users.

**Comment by DoctorMacc** [comment]
Davchoo made a PR with improvements that will be merged first to hopefully help with the fire charge "hit back" lag problem.

**Comment by DoctorMacc** [comment]
The laggy fireballs are not a perfect solution, but I'll look into fixing it for 1.16.100.

**Pull request merged**
