### PR TITLE
Update TODO inventory-blocks: grindstone

### PR DESCRIPTION
**Pull request by JamesTheAwesomeDude**
Re:
https://github.com/GeyserMC/Geyser/issues/1087
https://github.com/GeyserMC/Geyser/issues/1670

This is seemingly not yet fixed on `1.2.0-SNAPSHOT-561`; yet it's not listed under _either_ the "What's Left to be Added/Fixed" or "What can't be fixed" lists in the README.

This was tested with Spigot server, Switch client, Minecraft `1.6.4`.

### CODE REVIEW

**Comment by rtm516** [comment]
The current inventory system is being fully rewritten and fixes this issue.

**Comment by jackson-57** [comment]
It should still be noted in that section, as other inventories are listed there

**Comment by JamesTheAwesomeDude** [comment]
> It should still be noted in that section, as other inventories are listed there

Yes — unless the timeline for the inventory rewrite is coming in _very_ soon, I think it'd be for the best to have the publicly available documentation accurate. This was somewhat confusing for me, when my brother said Grindstones weren't working on his Switch, yet they were not listed among either the TODO or non-doable block lists.

**Comment by Camotoy** [comment]
I'll merge this whenever we have a code change. I'm hopeful for the inventory rewrite to be available soon, but yes, we might as well make it clear what currently does and does not work.

(We have a CI Skip feature on our build server, presumably, but the last time I checked it failed to work)

**Review by Camotoy — APPROVED** [review]

**Comment by Camotoy** [comment]
Thanks!

**Pull request merged**
