### PR TITLE
Dimension switching cleanup

### PR DESCRIPTION
**Pull request by Camotoy**
Cleans up dimension switching logic that should no longer be needed. Also fixes above Nether Bedrock building dimension switching.

### CODE REVIEW

**Review by rtm516 — APPROVED** [review]

**Comment by jkcoxson** [comment]
Is there a way to make Github regenerate artifacts here? I have tested it and it works with the current artifacts, and I just want to try it with newer commits that have happened since, or if you think it will just work it would be nice if this could be merged...

**Comment by Camotoy** [comment]
Sure, will do now.

**Comment by jkcoxson** [comment]
Sorry I didn't get back to this, just didn't have time to do a thorough testing yet.

**Comment by Camotoy** [comment]
No worries!

**Pull request merged**
