### PR TITLE
add more entityflags [WIP]

### PR DESCRIPTION
**Pull request by LegacyGamerHD**

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
this is not tested i also updated xd nummer am still working on stuff

**Comment by LegacyGamerHD** [comment]
if am doing stuff wron tell me because am a beginning to understand stuff just yet

**Comment by LegacyGamerHD** [comment]
i know the code style is messy but i will switch to intelji soon

**Comment by LegacyGamerHD** [comment]
if i get my bigger ssd

**Comment by lukeeey** [comment]
They were right the first time

**Comment by LegacyGamerHD** [comment]
@lukeeey I know that's why I closed the pull

**Pull request closed without merging**
