### PR TITLE
Fix movement issues

### PR DESCRIPTION
**Pull request by ForceUpdate1**

### CODE REVIEW

**Comment by Legit4K** [comment]
Tested on Standalone, seems to work

**Comment by DoctorMacc** [comment]
@ForceUpdate1 Would you be able to document how the teleport checking code works? I got quite tripped up trying to figure out how it all works myself.

Otherwise, thanks for the PR!

**Comment by rtm516** [comment]
> @ForceUpdate1 Would you be able to document how the teleport checking code works? I got quite tripped up trying to figure out how it all works myself.
> 
> Otherwise, thanks for the PR!

+ any missing Javadoc :)

**Comment by RednedEpic** [comment]
> @ForceUpdate1 Would you be able to document how the teleport checking code works? I got quite tripped up trying to figure out how it all works myself.
> 
> Otherwise, thanks for the PR!

It seems to be casting from float to double (and vice versa) causing the player's position to not be precise. This makes the Java server think that the player is inside of a block when they're really not, and send a movement correction packet.

**Pull request merged**
