### PR TITLE
fix some entity data type

### PR DESCRIPTION
**Pull request by caoli5288**
COLOR should be byte and HEALTH should be int.

### CODE REVIEW

**Comment by caoli5288** [comment]
In fact, this data value does not change the behavior of the client. So it doesn't matter if geyser send an wrong value, but it will cause the client to report an error.

> Assertion failed: Wrong value type for this ID!

This PR doesn't fix the obvious problem, but right code is always good, isn't it?

**Comment by Camotoy** [comment]
The color fix is fine; the health one is something that needs to be addressed. I believe the vanilla Bedrock server uses the health attribute for conveying health, and keeps the HEALTH entity metadata at 1.

**Comment by caoli5288** [comment]
> The color fix is fine; the health one is something that needs to be addressed. I believe the vanilla Bedrock server uses the health attribute for conveying health, and keeps the HEALTH entity metadata at 1.

yes. But at least we should send it with the correct type, and the value of HEALTH should obviously be an int in Bedrock.

**Comment by caoli5288** [comment]
Any review?

**Comment by Camotoy** [comment]
I don't feel comfortable with the health change, which needs a proper fix, and I'm unsure if this would break ender dragon code. The color change is fine.

**Comment by caoli5288** [comment]
@Camotoy There is only one situation that may cause problems. When the value of HEALTH is less than 1 but greater than 0 in Java version will become 0 after cast to int.

Obviously, sending HEALTH as a float cause client log an error. 

But I still don't think this value has any practical effect. The client obtains the life value of the entity through attributes rather than metadata. Maybe we can always set it to a fixed value, such as 20(I tested).

**Comment by Camotoy** [comment]
The health attribute issue is now obsolete with 32bbd8a.

**Comment by Camotoy** [comment]
This PR will be obsolete with 1.19 as COLOR is now, finally, a byte type. Thanks anyway!

**Comment by caoli5288** [comment]
> This PR will be obsolete with 1.19 as COLOR is now, finally, a byte type. Thanks anyway!

👍

**Pull request closed without merging**
