### PR TITLE
Add API for Music Packet

### PR DESCRIPTION
**Pull request by Kas-tle**
See https://minecraft.fandom.com/wiki/Commands/music

API allows for playing and queuing of multiple songs on Bedrock clients with the ability to fade between tracks and on stop.

Depends on: https://github.com/GeyserMC/Floodgate/pull/382

### CODE REVIEW

**Comment by Camotoy** [comment]
In general, it seems fine. Personally I don't think I want four new plugin channels for similar things - I'd rather just have them all under one plugin channel, and then read a byte to indicate what we're doing in that plugin message. Tim *might* have a different opinion though.

**Comment by Kas-tle** [comment]
CC @Tim203 otherwise will change it ^

**Comment by Tim203** [comment]
I was thinking the same thing.
And please make a PR over at [the api repo](https://github.com/GeyserMC/api).
I forgot to switch Geyser & Floodgate (feature/geyser-merge) to that repo.

**Comment by Kas-tle** [comment]
Closing as I would likely do this differently now.

**Pull request closed without merging**
