### PR TITLE
🔀 Merge with master (main?)

### PR DESCRIPTION
**Pull request by yakovliam**

### CODE REVIEW

**Comment by yakovliam** [comment]
That was a major mistake

**Comment by yakovliam** [comment]
Side note: Always test your server APIs in dev envs, and not connected to the actual repos.

**Comment by Camotoy** [comment]
Congratulations on being PR/issue number 1800! xd

**Comment by EasyClifton** [comment]
Why would you log credentials?

**Comment by yakovliam** [comment]
> Why would you log credentials?

This was a mistake PR, so please ignore. The purpose of logging was to debug a client-side issue that I was facing while entering ASCII text into the form. It was fixed through the client, not the server.

**Comment by yakovliam** [comment]
I would appreciate it if someone informed me how to permanently remove this PR from Geyser's PR history.

**Comment by Camotoy** [comment]
https://stackoverflow.com/a/18318431

**Pull request closed without merging**
