### PR TITLE
Bump MCAuthLib to 1.3-SNAPSHOT

### PR DESCRIPTION
**Pull request by AJ-Ferguson**

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
@AJ-Ferguson what about packet lib

**Comment by Tim203** [comment]
Shouldn't it be 1.2 since nothing changed from 1.2 to 1.3-SNAPSHOT and 1.2 is now finished while new commits can still be added to 1.3-SNAPSHOT

**Comment by AJ-Ferguson** [comment]
You're right.

**Comment by AJ-Ferguson** [comment]
Actually, it seems like `1.3-SNAPSHOT` is the only version we can use or else this happens.
```
java.lang.NoSuchMethodError: com.github.steveice10.mc.auth.data.GameProfile.setProperties(Ljava/util/List;)V
    at com.github.steveice10.mc.protocol.packet.ingame.server.ServerPlayerListEntryPacket.read(ServerPlayerListEntryPacket.java:61)
    at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:41)
```

**Pull request merged**
