### PR TITLE
Document Geyser methods and variables where possible

### PR DESCRIPTION
**Pull request by Camotoy**
This PR is mostly to go with the plugin API PR, and therefore most documentation is kept with that in mind.

### CODE REVIEW

**Comment by bundabrg** [comment]
This is great. I'm having some trouble with delombok and javadoc not playing nicely in the plugin PR but hopefully will get that sorted soon.

**Comment by lukeeey** [comment]
Why are you using Delombok?

**Comment by Tim203** [comment]
Floodgate 2.0 also has documentation for the Geyser common classes that are related to Floodgate btw.

**Comment by bundabrg** [comment]
Delombok is sadly needed to document setters and getters unless one wants to hand write them all out.

**Comment by Camotoy** [comment]
I'm closing this, as it's really no longer relevant in many places. If needed, I'll update Javadoc in places where we're going to update for API usage.

**Pull request closed without merging**
