### PR TITLE
Fixes errors related to skins

### PR DESCRIPTION
**Pull request by Tim203**

### CODE REVIEW

**Comment by RednedEpic** [comment]
Everything appeared to work just fine from my testing when it came to skins. Only issue I noticed was Optifine capes appeared not to be sized properly. Minecon capes appeared to be fine. Unsure if capes from MinecraftCapes, 5zig or LabyMod have these issues.

**Comment by LegacyGamerHD** [comment]
doesnt work for offline mode

[0;37mGot invalid texture data for insaneboy101 null[0m
[0;37mGot invalid texture data for insaneboy101 null[0m

**Comment by Tim203** [comment]
I'll fix it asap

**Comment by RednedEpic** [comment]
Fixes for offline mode coming shortly.

**Pull request merged**
