### PR TITLE
Remove render distance cap

### PR DESCRIPTION
**Pull request by AJ-Ferguson**

### CODE REVIEW

**Comment by rtm516** [comment]
Have you tested with 1.12 and 1.8 viaversion? (as the comment mentions it)

**Comment by AJ-Ferguson** [comment]
I've only done limited testing so far. Should definitely do more tests before merging.

**Comment by TheMasterBlaster** [comment]
Couldn't you make it a config option if there are issues with viaversion?

**Comment by DoctorMacc** [comment]
If there is an issue with ViaVersion we won't add a config option; we'll automatically detect it as we already check for ViaVersion and older versions for getting block states.

**Comment by TheMasterBlaster** [comment]
I use Standalone that's why I asked.

**Comment by DoctorMacc** [comment]
Tested ViaVersion Abstraction and ViaVersion 2.2.3 on Spigot 1.8.8 and 1.12.2 with no issues.

**Comment by DoctorMacc** [comment]
Going to close this as it will likely be removed via #1020.

**Pull request closed without merging**
