### PR TITLE
Java 1.21 support

### PR DESCRIPTION
**Pull request by Camotoy**
- [Geyser-Bungeecord.jar](https://download.geysermc.org/v2/projects/geyserpreview/versions/pr.4740/builds/latest/downloads/bungeecord)
- [Geyser-Fabric.jar](https://download.geysermc.org/v2/projects/geyserpreview/versions/pr.4740/builds/latest/downloads/fabric)
- [Geyser-NeoForge.jar](https://download.geysermc.org/v2/projects/geyserpreview/versions/pr.4740/builds/latest/downloads/neoforge)
- [Geyser-Spigot.jar](https://download.geysermc.org/v2/projects/geyserpreview/versions/pr.4740/builds/latest/downloads/spigot)
- [Geyser-Standalone.jar](https://download.geysermc.org/v2/projects/geyserpreview/versions/pr.4740/builds/latest/downloads/standalone)
- [Geyser-Velocity.jar](https://download.geysermc.org/v2/projects/geyserpreview/versions/pr.4740/builds/latest/downloads/velocity)
- [Geyser-ViaProxy.jar](https://download.geysermc.org/v2/projects/geyserpreview/versions/pr.4740/builds/latest/downloads/viaproxy)

### CODE REVIEW

**Comment by MasaharuShou** [comment]
does floodgate still works?

**Comment by Camotoy** [comment]
Yes. Make sure you're using the latest build.

**Comment by MasaharuShou** [comment]
btw did spigot 1.21 out yet? if its out will it work with that geyser?

**Review by Outfit8TSB — APPROVED** [review]
Yes. it must be merged.
to let [NogyangSpigot](https://github.com/GAME-CLI-SRV-DEV/NogyangSpigot) Work Intentionally as Crossplay Server, Geyser-Spigot is Required. NogyangSpigot and Geyser Must Update after it merged, otherwise they will have to use ViaVersion.
```NogyangSpigot-Paperclip-1.21-R0.1-SNAPSHOT-reobf.jar``` should release after merge.
how it works as a drawing:
```
                                                                 [Geyser]
                                                                      |
                             [NogyangSpigot]----[API]---[PluginManager]---[PluginClasses]
                                                           |       |
                                                           |----[Server]----[Bedrock]
```

**Comment by onebeastchris** [comment]
This will be merged as soon as ViaVersion releases their 1.21 builds - until then, this will stay as a separate branch. Otherwise, people who don't use 1.21 Java servers couldn't update Geyser.

**Comment by Outfit8TSB** [comment]
okay, then might as well we let [NogyangSpigot](https://github.com/GAME-CLI-SRV-DEV/NogyangSpigot) stay on 1.20.6 until ViaVersion 1.21 releases & this pull request is merged. until then, NogyangSpigot will do a final update. and then, NogyangSpigot will update to 1.21 Version of Paper new Pufferfish.

**Comment by PedroMPagani** [comment]
Can we make an addon as the team map clearing here?

**Pull request merged**
