### PR TITLE
Structure block translation

### PR DESCRIPTION
**Pull request by Camotoy**
- Translate structure block block entity (now renders in-world)
- Structure block GUI can be opened
- Mostly works - Bedrock cannot render previews since Java doesn't provide that data to us.

### CODE REVIEW

**Comment by YHDiamond** [comment]
I was thinking of doing this 😔

**Review by ProFireDev — APPROVED** [review]
nice work, its a lot cleaner to read now in some places too

**Comment by Tydium** [comment]
Hey is this ever gonna be merged with master? I've been waiting on it quite a bit keeping an eye on it.

**Comment by Camotoy** [comment]
The current bottleneck is that rotations do not match Java Edition.

**Comment by Tydium** [comment]
rip. Is there anyway that could be fixed?

**Comment by Camotoy** [comment]
Chris will have an updated version of this PR incoming. Hooray.

**Comment by Tydium** [comment]
I love you chris

**Pull request closed without merging**
