### PR TITLE
Massive code cleanup

### PR DESCRIPTION
**Pull request by rtm516**

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
would this improve performance

**Comment by Heath123** [comment]
> 
> 
> would this improve performance

It looks like it's mainly formatting and spacing

**Comment by rtm516** [comment]
Yea it's all just formatting, shouldn't affect performance stall. Maybe change build times as I removed any unused imports.

**Comment by RednedEpic** [comment]
Will be merging this one sounds makes it into master.

**Comment by Heath123** [comment]
> 
> 
> Will be merging this one sounds makes it into master.

Isn't that now?

**Pull request closed without merging**
