### PR TITLE
Allow for crawling and moving in one-block spaces where possible

### PR DESCRIPTION
**Pull request by Camotoy**
This commit brings full support for crawling, sneaking under 1.75-block-tall spaces, and swimming in one-block areas. There is a check in place that decreases the player's speed to something comparable to Java if they are in a situation where they would otherwise go at normal walking speed (for example: without the check, a Bedrock player would go at full walking speed while crawling.

### CODE REVIEW

**Review by rtm516 — APPROVED** [review]

**Comment by Camotoy** [comment]
!start-test-server

**Comment by Camotoy** [comment]
!start-test-server

**Comment by Camotoy** [comment]
This *does* break swimming on 1.13.2, which while certainly not the end of the world, is not a regression I'd like to introduce.

**Comment by YHDiamond** [comment]
You said it breaks swimming, does this mean you won't implement it without re-fixing swimming or will it be OK?

**Comment by Camotoy** [comment]
I don't plan on merging this until there are no known regressions.

**Comment by datrandomduggy** [comment]
anyway this could be added to the inventory branch?

**Comment by Hellohi3654** [comment]
> anyway this could be added to the inventory branch?

https://github.com/Hellohi3654/Geyser/releases/latest

**Comment by Camotoy** [comment]
The above branch is untested and unsupported by Geyser.

**Comment by Hellohi3654** [comment]
> The above branch is untested and unsupported by Geyser.

Sorry I edited it

**Comment by Camotoy** [comment]
This PR is back in business - I realized that the client is a bit more authoritative when it comes to setting sneaking and swimming. The only downside is that, if a player unsneaks, they get stuck in the block until they sneak again, but I'm fine with that behavior/I might fix that.

**Comment by Olexorus** [comment]
Hey, just wondering, what's the current state of this?
It seems to fix some issues with my anti cheat, so it would be really cool to see this merged 😄

**Comment by Hellohi3654** [comment]
> Hey, just wondering, what's the current state of this?
> It seems to fix some issues with my anti cheat, so it would be really cool to see this merged 😄

I have this merged into my fork of Geyser if you want to use it now

**Comment by Olexorus** [comment]
> 
> 
> > Hey, just wondering, what's the current state of this?
> > It seems to fix some issues with my anti cheat, so it would be really cool to see this merged 😄
> 
> I have this merged into my fork of Geyser if you want to use it now
> 
> You can also download this PR from checks

Thanks, I'm aware, that's why I know it fixes some stuff. But I meant the anti cheat I'm developing (https://www.spigotmc.org/resources/themis-anti-cheat-1-16-x-bedrock-support-paper-tuinity-compatibility-free-optimized.90766/), and I can't really the user they need to download some special build with this patch😅

**Pull request merged**
