### PR TITLE
Add a warning at start about movement translation

### PR DESCRIPTION
**Pull request by E404NNF**
This is just a PR which will warn the user everytime they start Geyser that movement isn't perfect and might get the user banned from a server

### CODE REVIEW

**Comment by Heath123** [comment]
Maybe use a translation string?

**Comment by E404NNF** [comment]
ah forgot about other languages

**Comment by E404NNF** [comment]
i don't know how to use translation strings, can you help me with it?

**Comment by E404NNF** [comment]
oh i understand now

**Pull request closed without merging**
