### PR TITLE
Merge Fabric support

### PR DESCRIPTION
**Pull request by SupremeMortal**
Merge Fabric support from the [original repo](https://github.com/GeyserMC/Geyser-Fabric)

### CODE REVIEW

**Comment by onebeastchris** [comment]
ayyyy let's go!

**Comment by Konicai** [comment]
For floodgate, I fixed the ASM issue by adding loom 1.0-SNAPSHOT to the root project but not applying it (as recommended by modmuss). And I'm pretty sure the only reason my floodgate-fabric is failing is because the mod is empty.

I just tried that now for this but still ran into the classfile version error when relocating 😕. Maybe I'm forgetting something else I did.

**Comment by SupremeMortal** [comment]
> For floodgate, I fixed the ASM issue by adding loom 1.0-SNAPSHOT to the root project but not applying it (as recommended by modmuss). And I'm pretty sure the only reason my floodgate-fabric is failing is because the mod is empty.
> 
> I just tried that now for this but still ran into the classfile version error when relocating 😕. Maybe I'm forgetting something else I did.

I ended up deploying a snapshot version of the shadow plugin to the opencollab repo, which resolved it. We can remove that whenever they get around to releasing 7.1.3.

**Comment by Konicai** [comment]
Cool. On a different note, we should add Geyser Fabric to the github actions archive step

**Review by Camotoy — APPROVED** [review]

**Pull request merged**
