### PR TITLE
Add minimum delay between closing and opening a new window

### PR DESCRIPTION
**Pull request by AJ-Ferguson**
Should fix new windows not showing up with some plugins like Lottery.

### CODE REVIEW

**Comment by AnonAlpha** [comment]
I thought pull request #602 should fix this problem?

**Comment by Kadnick** [comment]
Fix works! Thanks!

**Comment by DoctorMacc** [comment]
There were some remaining inventory problems, Anon.

**Comment by AnonAlpha** [comment]
> There were some remaining inventory problems, Anon.

Thanks!

**Pull request merged**
