### PR TITLE
Move fixes v2 (WIP, testing needed)

### LINKED ISSUE #204: Player can't move correctly when cord number is higher than 4096 / Slab and stair issues
**Describe the bug**
Players get dragged back by server when walking near a wall or getting out of water

**To Reproduce**
1. Use the newest inventory branch
2. build a wall two block(or higher) high
3. Walk near it

**Expected behavior**
Players can walk normally

**Screenshots**
See attached video file
video 1 and 2 for walking near wall
video 3 for getting out of water

**Server version**
spigot 1.15.2 latest build
**Geyser version**
Latest inventory branch

**Bedrock version**
Latest

**Additional context**
[video1](https://discordapp.com/channels/613163671870242838/613168464634576897/686762472522514515)
[video2](https://discordapp.com/channels/613163671870242838/613168464634576897/686762486401466388)
[video3:](https://discordapp.com/channels/613163671870242838/613168464634576897/686767428394287104)

### PR DESCRIPTION
**Pull request by Heath123**
Move fixes V2 using bounding boxes
This has some performance optimisations that could potentially cause problems, now or in the future:
1) It currently only checks block underneath the player by treating the height as 0
2) It doesn't check collision unless the Y position changes
3) It doesn't check collision when onGround isn't set, causing problems when flying into a stair in creative

**Known bugs to fix**
- [x] ~~Sometimes when sprinting up stairs you get teleported back~~ Fixed!
- [ ] Snow layers are a bit buggy (disabling optimisations 2 and 3 at the same time seems to help)
- [ ] Add proper hitboxes for:
- Fences and walls (also with carpets on top)
- Fence gates
- Beds
- Flower pots
- Skulls
- Grindstone

**Todo**
- [ ] Try to fix -40 barrier causing player not to die
- [ ] Reproduce and fix #204 and https://github.com/GeyserMC/Geyser/issues/682

Please tell me about any more bugs you find!

### CODE REVIEW

**Comment by TheMasterBlaster** [comment]
Iv done some basic testing on Standalone and it seems this makes moving up stairs/slabs/blocks (picture below) harder to do then in current Geyser.
image

**Comment by SinanGentoo** [comment]
Unfortunately, I tried to merge the branch and try to compile, and the problem of not being able to walk on non-full blocks with coordinates greater than 4096 still exists

**Comment by Heath123** [comment]
> Unfortunately, I tried to merge the branch and try to compile, and the problem of not being able to walk on non-full blocks with coordinates greater than 4096 still exists

That isn't what I was trying to solve but I'll see if I can do something about that

**Comment by Heath123** [comment]
> Iv done some basic testing on Standalone and it seems this makes moving up stairs/slabs/blocks (picture below) harder to do then in current Geyser.
> image

Thank you, I'll rebuild that and try to reproduce it

**Comment by TheMasterBlaster** [comment]
> > Iv done some basic testing on Standalone and it seems this makes moving up stairs/slabs/blocks (picture below) harder to do then in current Geyser.
> > image
> 
> Thank you, I'll rebuild that and try to reproduce it

The cords I'm at are about -513 53 8710, The current Geyser standalone handles it pretty well from my Skynode Host. When I home hosted it, it was super unstable(almost impossible to walk up it. if that helps at all :)

**Comment by Heath123** [comment]
> > > Iv done some basic testing on Standalone and it seems this makes moving up stairs/slabs/blocks (picture below) harder to do then in current Geyser.
> > > image
> > 
> > 
> > Thank you, I'll rebuild that and try to reproduce it
> 
> The cords I'm at are about -513 53 8710, The current Geyser standalone handles it pretty well from my Skynode Host. When I home hosted it, it was super unstable(almost impossible to walk up it. if that helps at all :)

Ah, that's probably the 4096 issue

**Comment by AnonAlpha** [comment]
Yes the 4096 problem happen again, inside 4096 range, it's all fine, but out, there are issue #204 again

**Comment by Heath123** [comment]
Can some more people test please? I fixed some things

**Comment by Heath123** [comment]
@TheMasterBlaster Could you try to reproduce it again on the latest version please?

**Comment by Heath123** [comment]
Sorry, closed by accident
Use https://github.com/GeyserMC/Geyser/pull/699

**Pull request closed without merging**
