### PR TITLE
Implement particles.

### PR DESCRIPTION
**Pull request by BeerMC**

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
ehh why is my stuff in it from my fork

**Comment by LegacyGamerHD** [comment]
@BeerMC remove my stuff

**Comment by BeerMC** [comment]
> ehh why is my stuff in it from my fork

emm I made a mistake...
I will send to your fork...

**Comment by Heath123** [comment]
> > ehh why is my stuff in it from my fork
> 
> emm I made a mistake...
> I will send to your fork...

That fork isn't maintained

**Comment by Heath123** [comment]
You need to update this to the latest master version

**Comment by Heath123** [comment]
Maybe I should do that

**Comment by BeerMC** [comment]
> You need to update this to the latest master version

> Maybe I should do that

I am a little busy...
So I will be happy if you can help to make a pull request to GeyserMC/Geyser.

**Comment by Heath123** [comment]
I'll try to port the changes over to master and make a new PR

**Comment by LegacyGamerHD** [comment]
> > > ehh why is my stuff in it from my fork
> > 
> > 
> > emm I made a mistake...
> > I will send to your fork...
> 
> That fork isn't maintained

it is maintained stop saying that

**Comment by Heath123** [comment]
> > > > ehh why is my stuff in it from my fork
> > > 
> > > 
> > > emm I made a mistake...
> > > I will send to your fork...
> > 
> > 
> > That fork isn't maintained
> 
> it is maintained stop saying that

I thought you said it wasn't because the inventory branch has everything 
What does your fork have?

**Comment by LegacyGamerHD** [comment]
block breaking animation particles

**Comment by LegacyGamerHD** [comment]
some other stuff

**Comment by Heath123** [comment]
Oh

**Comment by Heath123** [comment]
Maybe I should use yours then

**Comment by EOT3000** [comment]
wait. BeerMC? Like Beer Spigot 🤔

**Pull request closed without merging**
