### PR TITLE
Fix closing inventory confirmation behavior

### PR DESCRIPTION
**Pull request by that-apex**
Fixes an issue with Geyser thinking that an inventory is open where it's actually not open for the client.

With the current code it is possible for the following situation to happen:
- server sends an open inventory packet and then immediately a close inventory packet
- the open inventory packet is handled on Geyser, `openInventory` is called, this sets the open inventory via `session.setOpenInventory` and schedules a task in an event loop that does further processing.
- the close inventory packet is handled **before** the event loop task runs, which sets the openInventory to `null` and then awaits the inventory to close by setting `closingInventory` to `true`
- only now the event loop task runs, but `openInventory` is already set to `null` so it doesn't do anything
- we have a situation in which `openInventory` is `null`, there is no inventory opened for the client but `closingInventory` is set to `true` which makes it impossible to open new inventories because Geyser still waits for the old inventory to close

This PR fixes this issue by making it so close confirmation is not required if the inventory wasn't opened in the first place.

### CODE REVIEW

**Comment by Camotoy** [comment]
Hi, thanks for the PR!

Can you elaborate on the purpose of this PR? Does it solve a bug?

**Comment by that-apex** [comment]
I edited the description to explain the issue.

**Comment by Camotoy** [comment]
Thanks for waiting. I've asked another developer to help review this, since inventory code has always leaned on the interesting side. He did point out that you only enable setDisplayed for double chests - other inventories don't get the boolean enabled.

**Comment by that-apex** [comment]
It's fixed now

**Review by AJ-Ferguson — APPROVED** [review]

**Comment by Camotoy** [comment]
Thank you for the contribution!

**Pull request merged**
