### PR TITLE
Update build.gradle.kts

### PR DESCRIPTION
**Pull request by raitako-1**
When I built it, delombok did not work, so I fixed it.

### CODE REVIEW

**Comment by Kas-tle** [comment]
Could you please clarify what error you're getting? I don't think we've had any issues with Lombok.

**Comment by Konicai** [comment]
What is your exact IDE version?

**Comment by raitako-1** [comment]
`Configuration on demand is an incubating feature.
Type-safe project accessors is an incubating feature.

> Configure project :
Project accessors enabled, but root project name not explicitly set for 'build-logic'. Checking out the project in different folders will impact the generated code and implicitly the buildscript classpath, breaking caching.

> Configure project :fabric
Fabric Loom: 1.0.18

> Task :standalone:delombok
Exception in thread "main" java.lang.AssertionError: Unhandled tree type: class com.sun.tools.javac.tree.JCTree$JCConstantCaseLabel: "--gui"
        at lombok.delombok.PrettyPrinter.visitTree(PrettyPrinter.java:1676)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$Visitor.visitConstantCaseLabel(JCTree.java:3526)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCConstantCaseLabel.accept(JCTree.java:2327)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:226)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:240)
        at lombok.delombok.PrettyPrinter.visitCase(PrettyPrinter.java:1348)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCase.accept(JCTree.java:1328)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:226)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:240)
        at lombok.delombok.PrettyPrinter.visitSwitch(PrettyPrinter.java:1397)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1287)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:226)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:240)
        at lombok.delombok.PrettyPrinter.visitBlock(PrettyPrinter.java:1133)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1082)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:226)
        at lombok.delombok.PrettyPrinter.visitForLoop(PrettyPrinter.java:1251)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCForLoop.accept(JCTree.java:1182)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:226)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:240)
        at lombok.delombok.PrettyPrinter.visitBlock(PrettyPrinter.java:1133)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1082)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:226)
        at lombok.delombok.PrettyPrinter.visitMethodDef(PrettyPrinter.java:857)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:912)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:226)
        at lombok.delombok.PrettyPrinter.printClassMembers(PrettyPrinter.java:617)
        at lombok.delombok.PrettyPrinter.visitClassDef(PrettyPrinter.java:556)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:810)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:226)
        at lombok.delombok.PrettyPrinter.visitTopLevel(PrettyPrinter.java:482)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:549)
        at lombok.delombok.DelombokResult.print(DelombokResult.java:74)
        at lombok.delombok.Delombok.delombok(Delombok.java:819)
        at lombok.delombok.Delombok.main(Delombok.java:326)
        at lombok.delombok.DelombokApp.runDirectly(DelombokApp.java:176)
        at lombok.delombok.DelombokApp.runApp(DelombokApp.java:47)
        at lombok.core.Main.go(Main.java:130)
        at lombok.core.Main.main(Main.java:43)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at lombok.launch.Main.main(Main.java:46)

> Task :standalone:delombok FAILED`

I got this error during the build.
I'm new to github so I'm not sure, but I just did a git clone, git submodule update --init --recursive and ran gradlew.bat build.
After that, I did some research and found that it was really gibberish, so I somehow rewrote the plugin version to a newer one and the build succeeded, so I requested this fix.

**Comment by raitako-1** [comment]
`id("io.freefair.lombok") version "6.6.2" apply false`
It might be good because it works here too. Maybe it's a snake oil thing.

**Comment by Konicai** [comment]
I'm 99% sure that this is an IDE or plugin version issue. There are devs running IDEA and Eclipse, none of which have this issue.

**Pull request closed without merging**
