### PR TITLE
Minecraft Bedrock: Paid Skins for PayPal Only.

### PR DESCRIPTION
**Pull request by mrnotesonic**
Minecraft Bedrock needs in your game that needs
Paid Skins for money.
Other stuff.
And more.
Probably going to close this as a draft.

### CODE REVIEW

**Comment by mrnotesonic** [comment]
Reopened if you like to do some stuff.

**Comment by mrnotesonic** [comment]
I think this pull request can be merged if you like to merge it.

**Comment by RednedEpic** [comment]
I have no clue what you’re doing here... the only thing this contains is a WIP branch I was working on for forms support through GeyserAddons. It will be merged when it’s ready.

**Comment by mrnotesonic** [comment]
Alrighty,

**Pull request closed without merging**
