### PR TITLE
Fix building on Gradle 8.0

### PR DESCRIPTION
**Pull request by skbeh**

### CODE REVIEW

**Comment by Konicai** [comment]
The Java version should be kept at 16 for now - and I'm not sure why it says the current Java target is 17 in your log 🤔

**Comment by skbeh** [comment]
@Konicai It is set in https://github.com/GeyserMC/Geyser/blob/30277d54114de100175b20b4257a55314409723b/build-logic/src/main/kotlin/geyser.base-conventions.gradle.kts#L30

**Comment by skbeh** [comment]
@Konicai I think that it is pointless to support deprecated java versions.

**Comment by Konicai** [comment]
Geyser will be updated to Java 17 in the near future, but as far as I know we are going to make a warning announcement first, and then wait some more time. 

Why is it saying "current target is 17" when it isn't configured that way? That seems to be the root issue

**Comment by skbeh** [comment]
Maybe because Gradle 8.0 changed some defaults.

**Comment by Camotoy** [comment]
Konica beat me to it, but yeah, we still need to support 16 until we properly deprecate support. (6.8% of users / 1491 instances still use Java 16)

**Comment by Camotoy** [comment]
Do note that for building, one needs Java 17, so as long as every jar file is compiled to Java 16 besides Fabric that's fine.

**Comment by skbeh** [comment]
It would be safe to set jvm target of kotlin to Java 17 because kotlin is only used for build script in the project.

**Comment by skbeh** [comment]
@Konicai ping

**Comment by skbeh** [comment]
ping

**Comment by Jens-Co** [comment]
> ping

Please don't unnecessary bump issues/pr's.

**Comment by Konicai** [comment]
Superseded by #3781

**Comment by skbeh** [comment]
@Konicai As what I see, the two pull requests are not conflict.

**Pull request closed without merging**
