### PR TITLE
Added basic data storage as a placeholder for caching.

### PR DESCRIPTION
**Pull request by ProPane865**
This will make a file and put all values for basic data such as player names. We may need to update/optimize it to add more data than just player names. For now, this is just a placeholder.

### CODE REVIEW

**Comment by lukeeey** [comment]
Whats the point of this

**Comment by RednedEpic** [comment]
Those lines of code are only temporary and will be replaced with the proper data at a later date, hence the TODO. Caching the temporary data that will shortly be replaced with a better method is not ideal.

**Comment by lukeeey** [comment]
But its called "temporary" data.

**Comment by RyanHecht** [comment]
Do we really need a persistent cache? Surely an in-memory cache would be more performant/fine for our purposes?

**Pull request closed without merging**
