### PR TITLE
Fix dropped items

### PR DESCRIPTION
**Pull request by AJ-Ferguson**

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
lmao my hero XD

**Comment by Heath123** [comment]
> lmao my hero XD

It's not that good...
It's just a tiny visual change

**Comment by LegacyGamerHD** [comment]
> > lmao my hero XD
> 
> It's not that good...
> It's just a tiny visual change

can you not argue about everyting am posting he did it in day while i coulded get it working

i got a shop with slaps were items are on in factions so yeah it importand for me

**Comment by Heath123** [comment]
Ah, OK. I was just wondering why you seemed si happy. This is really good, but crafting is really needed to make normal survival playable.

**Pull request merged**
