### PR TITLE
Prevent invalid stonecutter recipes from causing bedrock players to not be able to craft

### PR DESCRIPTION
**Pull request by Setadokalo**
I don't know if this can *only* occur when the server has block-adding mods, but I think completely failing to let players craft any items at all would qualify as "bad behavior". This PR filters items from the stonecutter recipe list which would otherwise trigger a NullPointerException, so only the invalid item will be uncraftable, not *all* items.

### CODE REVIEW

**Comment by Camotoy** [comment]
If an invalid item is sent as a recipe, where does the NPE happen?

**Comment by Setadokalo** [comment]
the line immediately after the check:
```java
data.getValue().sort(Comparator.comparing((stoneCuttingRecipeData ->
                    ItemRegistry.getItem(stoneCuttingRecipeData.getResult()).getJavaIdentifier())));
```
In my testing I believe I found that it could happen both on `ItemRegistry.getItem()` and on `.getJavaIdentifier()`. The ingredient null checks might not be necessary - They weren't for my case, at least.

**Comment by Camotoy** [comment]
I don't think a stream is necessary here (streams are generally regarded as not the best thing to use anyway). What I would do is, in the comparator lambda, save the result of the ItemEntry to a variable. if it's null, return `""`. Otherwise, return the Java identifier as normal. 
The `getJavaIdentifier()` should never be null.
then at:
```java
ItemData input = ItemTranslator.translateToBedrock(session, ingredient);
ItemData output = ItemTranslator.translateToBedrock(session, stoneCuttingData.getResult());
```
you can do a `if input.getId() == 0 { continue; }` if you want.

**Comment by Camotoy** [comment]
I handled this in https://github.com/GeyserMC/Geyser/commit/a5779a716bfb0d5cfd84eebaf41cd999bd56c021 and added you as a co-author. Thanks!

**Pull request closed without merging**
