### PR TITLE
fix spawn item twice or more

### PR DESCRIPTION
**Pull request by caoli5288**
Correct spawn method and fix spawn twice when spigot processing item merge.

### CODE REVIEW

**Comment by Camotoy** [comment]
Could you describe what bug this fixes and/or how to replicate this? Thanks!

**Comment by caoli5288** [comment]
If you look at the console log, you will find this error report.

1. when spawn item: 
Geyer send an AddEntityPacket(at Entity.spawnEntity) and an AddItemEntityPacket(at ItemEntity.updateBedrockMetadata) with same entity id.

2. when spigot do item merge
Geyser send two AddItemEntityPacket(at ItemEntity.updateBedrockMetadata)

Both of these behaviors will cause the client to report an error (but not damage the function)

**Comment by Camotoy** [comment]
I would definitely appreciate comments in the code explaining that. Additionally, I think the code would look cleaner if it looked something like https://github.com/GeyserMC/Geyser/blob/master/connector/src/main/java/org/geysermc/connector/entity/WitherSkullEntity.java#L48 - we don't need to check for validity on entity metadata send; just despawn the old entity and create a new one right away.

**Comment by caoli5288** [comment]
> I would definitely appreciate comments in the code explaining that. Additionally, I think the code would look cleaner if it looked something like https://github.com/GeyserMC/Geyser/blob/master/connector/src/main/java/org/geysermc/connector/entity/WitherSkullEntity.java#L48 - we don't need to check for validity on entity metadata send; just despawn the old entity and create a new one right away.

You're right. I'll update this PR soon.

**Comment by Camotoy** [comment]
The logic looks fine to me, but I won't be able to test this until Monday unless someone else does.

**Review by Camotoy — APPROVED** [review]

**Comment by Camotoy** [comment]
Thanks!

**Pull request merged**
