### PR TITLE
Implement entity spectating

### PR DESCRIPTION
**Pull request by lukeeey**
### Introduction
This PR implements #1334. It is not the best way by a long shot, but it's all we have until bedrock implements it.

At the time of writing, this PR \*works\*. There is a few debug messages in there and the teleporting is extremely glitchy (i heard short range teleports aren't great?), but it works.

### TODO
- [ ] Fix the glitchy teleports
- [ ] Only forward move packets every 10 ticks / 1 second?
- [ ] Change the position slightly so you aren't inside the entity you're spectating
- [ ] Make the player invisible to itself

### CODE REVIEW

**Comment by vijaypondini** [comment]
Well, I tested this before you completed said tasks, and found a few other issues that happened. ( By the way thank you for making a new pull request devoted specifically to my issue and spectator gammeode! )

https://youtu.be/LqoWmGMPP1Y

You will see in this video, spectating works nicely. I used my java account, and played on mobile. After a few seconds though, I automatically stop spectating and get teleported to y 256 in spectator mode. 
We can now actually fly up and down in spectator, so you can consider that a fix :)
Sometimes the chunks have an issue after finishing spectating, don't know if that's an issue on the plugins' end.
First person view, am inside the person's head, but as you have put in the TODO list that you need to change the player position slightly, I have left it at that. 

Third person back view is nice, but you don't move in the camera perspective of the player you are spectating ( you'll have to manually move yourself around his camera view ). That might be the reason that entity spectating stops because it glitches out when it can't make that camera movement effect..

Halfway into the video spectating by even moving a couple of blocks don't work, relogging seems to have fixed the issue. I am unsure why that happened, but yeah.

All in all - 
- Change position slightly ( as you mentioned )
- Allow camera movement during spectating of players.
- Teleportation to the Y level issue
- Chunk loading issue

**Comment by lukeeey** [comment]
I haven't been working on this because of those weird teleportation issues. I have absolutely no idea what is causing them.
You seen to be having better luck than me with it, though. It worked for a few seconds before glitching out and i didn't even get that luxury...

Once the teleportation issues are fixed ill address the other problems would should be quite easy.

**Comment by vijaypondini** [comment]
Well I think the camera rotation should move along with the spectator. I think for players moving backward, or if they move 180 degrees and walk, the spectating of the entity probably errors and then tps you out.
I think that's probably one of the reasons

**Comment by vijaypondini** [comment]
Is this pr being worked on?

**Comment by gaming32** [comment]
This is great work! Please keep working on it! (I’ll see if I can get a Kava environment set up to make a PR of the PR :)

**Comment by lukeeey** [comment]
@gaming32 issues with teleporting stopped me working on this

**Comment by gaming32** [comment]
It appears that this bug occurs when the "playerEntityId" is the same as the "cameraEntityId". I don’t know enough about the Geyser API to know if this is what’s causing the sudden exits from spectating mode, but I *do* think the teleportation issue is an issue with `stopSpectatingEntity`.

**Comment by Redned235** [comment]
Stale PR - closing. Bedrock also has a camera feature which may make this far more feasible to implement, which would require an entirely new implementation as well.

**Pull request closed without merging**
