### PR TITLE
change the api not found error message

### PR DESCRIPTION
**Pull request by onebeastchris**
Thanks to Jens for noticing; i put the error logger on the wrong line. This PR removes the previous addition, and changes the message I intended to change instead. I've also left if to print the error; although it technically could be removed.

### CODE REVIEW

**Review by Jens-Co — APPROVED** [review]
Looks good to me!

**Comment by Camotoy** [comment]
Seems like we're assuming the error here a little too much, since connection issues might not always be what fires here (I assume). I'd either re-word it so we're saying that the API might *not* be the problem, or put this new message under `if (ex instanceof SpecificApiErrorException)`.

**Comment by Tim203** [comment]
I'm not sure if I'm a fan of hardcoding the hostname regardless that it'll never change.
Maybe the message can be reworded to say something like: Unable to resolve the skin api

**Comment by onebeastchris** [comment]
Valid points, yea
Although i can't seem to find an SpecificApiErrorException to check for; looking at the past errors it's just an UnknownHostException
I'd just add a check for that to print the new message, and if that too fails, the old style of error wont imply a connection issue

**Comment by Camotoy** [comment]
SpecificApiErrorException was an example. It doesn't actually exist.

**Comment by onebeastchris** [comment]
ah, excellent
see, i take things you say at face value, so uh, nice
Anyways, i've added a commit with the changes, i hope that's better

**Comment by Camotoy** [comment]
Looks fine, but I see that Tim sent other connection exceptions to debug mode. Perhaps we should do the same here?

**Comment by onebeastchris** [comment]
As in, print the warning but log the actual error only in debug mode?

**Comment by onebeastchris** [comment]
i cannot edit this pr anymore, as my initial branch was deleted - i'll reopen this PR & recreate the changes

**Pull request closed without merging**
