### PR TITLE
Fix: protocol being null during online mode login

### PR DESCRIPTION
**Pull request by onebeastchris**
This causes protocol.getState() to throw with an NPE
should resolve e.g. https://mclo.gs/4sraMM5

### CODE REVIEW

**Comment by Camotoy** [comment]
This fix is fine, but we should probably stop before sendDownstreamPacket is even sent (I.E. do a check for logged in at the beginning of a packet translator). Can you attach a stack trace if debug mode is enabled?

**Comment by onebeastchris** [comment]
Not sure we can do that in the translator, since the packet translator handles both bedrock and java packets? we might accidentally block the login detail form response

**Comment by Camotoy** [comment]
Just something like https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockMovePlayerTranslator.java#L49 where necessary.

**Comment by onebeastchris** [comment]
Unless i'm fully wrong, we'd have to add these on most bedrock packet translators then? aka movement, server settings packets, inventory and technically even chat one..
This PR would just restore the behavior from before we were checking the protocol state - the sendDownstreamPacket() method does a null check on downstreamsession in order to prevent cases as these (https://github.com/GeyserMC/Geyser/blob/4e1e720b3f6d0285c57ac36efd652bfa4dff4ce3/core/src/main/java/org/geysermc/geyser/session/GeyserSession.java#L1655)

**Comment by Camotoy** [comment]
Hmm, fair enough. Do add a stack trace check juuuuuust in case?

**Comment by onebeastchris** [comment]
sure, will add it shortly
just get the current thread and dump that into debug mode?

**Comment by onebeastchris** [comment]
Added debug printing, should be good to go now

**Review by Kas-tle — APPROVED** [review]

**Review by Camotoy — APPROVED** [review]

**Pull request merged**
