### PR TITLE
Do some null checking on shields

### PR DESCRIPTION
**Pull request by DoctorMacc**
Prevents NPEs from occuring.

### CODE REVIEW

**Comment by lukeeey** [comment]
Why would the player inventory ever be null at that point?

**Comment by DoctorMacc** [comment]
> Why would the player inventory ever be null at that point?

Yeah, I don't deny it might be excessive.

**Comment by RednedEpic** [comment]
I think a better approach would be to figure out why the inventory is returning null and fix that rather than adding a null check in this one place.

**Comment by DoctorMacc** [comment]
Closing this for now since it hasn't been reported by anyone else (so it's not a major issue) and it doesn't fix the problem, whatever it may be.

**Pull request closed without merging**
